export const ROUTES = {
  LOGIN: "login",
  REGISTER: "register",
  MENU: "menu",
  IMC: "imc",
  EER: "eer",
  TMB: "tmb",
  GET: "get",
  GC: "gc",
  MI: "mi",
  PESO: "peso",
  PROFILE: "profile",
  WHTR: "whtr",
  RCQ: "rcq",
  RCEST: "rcest",
  RESET_PASSWORD: "reset-password",
  NAF: "naf",
  HIDRICA: "hidrica",
  MACRO: "macro",
};
