import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

const styles = StyleSheet.create({
  screen: {
    paddingHorizontal: 20,
    paddingTop: 40,
    paddingBottom: 120,
  },
  keyboardAvoider: {
    flex: 1,
  },
  content: {
    gap: 20,
    paddingBottom: 20,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  avatar: {
    width: 52,
    height: 52,
    alignItems: "center",
    justifyContent: "center",
  },
  headerText: {
    flex: 1,
    gap: 6,
  },
  kicker: {
    color: "rgba(255,255,255,0.76)",
    letterSpacing: 1,
    fontWeight: "800",
    fontSize: 12,
  },
  title: {
    color: colors.surface,
    fontSize: 24,
    fontWeight: "900",
    letterSpacing: -0.2,
  },
  subtitle: {
    color: "rgba(255,255,255,0.9)",
    lineHeight: 20,
  },
  cardLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cardLabelGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  cardLabel: {
    color: colors.surface,
    fontWeight: "800",
    fontSize: 16,
    letterSpacing: 0.2,
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(231,237,245,0.92)",
    borderWidth: 1,
    borderColor: "rgba(28,60,90,0.12)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 50,
  },
  badgeText: {
    color: "#1c3c5a",
    fontWeight: "800",
    fontSize: 12,
  },
  cardContainer: {
    width: "100%",
    aspectRatio: 1.6,
    alignSelf: "center",
    perspective: 1000,
    position: "relative",
  },
  cardFace: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 22,
    overflow: "hidden",
    backfaceVisibility: "hidden",
    shadowColor: "#0d2f57",
    shadowOpacity: 0.24,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
  },
  identityCard: {
    flex: 1,
    borderRadius: 22,
    paddingVertical: 8,
    paddingHorizontal: 10,
    overflow: "hidden",
    position: "relative",
  },
  cardBack: {
    flex: 1,
    backgroundColor: "#4b6a8f",
    padding: 18,
    gap: 14,
    alignItems: "stretch",
    justifyContent: "flex-start",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
  },
  cardOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,255,255,0.1)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  cardDots: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    overflow: "hidden",
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 12,
    paddingTop: 10,
    gap: 2,
  },
  cardDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "rgba(255,255,255,0.16)",
    margin: 3,
  },
  identityHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginBottom: 10,
  },
  crestBlock: {
    alignItems: "center",
    gap: 6,
  },
  crestCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0,
    backgroundColor: "transparent",
    marginTop: -8,
  },
  crestLogo: {
    width: 78,
    height: 78,
    tintColor: "#f2f6ff",
  },
  crestText: {
    color: "#e9fbff",
    fontWeight: "900",
    letterSpacing: 1,
    fontSize: 10,
    marginTop: 2,
  },
  crestRibbon: {
    flexDirection: "row",
    gap: 3,
    marginTop: -12,
  },
  ribbonStripe: {
    width: 14,
    height: 6,
    borderRadius: 2,
  },
  ribbonGreen: { backgroundColor: "#e8eef9" },
  ribbonYellow: { backgroundColor: "#c7d4ec" },
  ribbonBlue: { backgroundColor: "#a9bee2" },
  identityHeaderText: {
    flex: 1,
    gap: 2,
    alignItems: "center",
  },
  councilTitle: {
    color: "#e6eaef",
    fontWeight: "900",
    fontSize: 16,
    letterSpacing: 0.8,
    textAlign: "center",
  },
  councilSubtitle: {
    color: "#d8dee6",
    fontWeight: "800",
    fontSize: 9,
    letterSpacing: 0.4,
    textAlign: "center",
  },
  cardHeading: {
    color: "#e8ecf3",
    fontWeight: "900",
    fontSize: 13,
    letterSpacing: 0.6,
  },
  identityBody: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-start",
    marginTop: 4,
  },
  identityLeft: {
    width: 110,
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    gap: 14,
    paddingTop: 0,
    paddingLeft: 0,
  },
  identityLeftTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingLeft: -4,
  },
  identityDocsRow: {
    marginTop: 14,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    justifyContent: "space-between",
    width: "100%",
    flexWrap: "nowrap",
  },
  identityChip: {
    width: 60,
    height: 42,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "#59789e",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
    shadowColor: "#0a1c30",
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    position: "relative",
    transform: [{ translateY: 16 }],
  },
  identityChipFill: {
    ...StyleSheet.absoluteFillObject,
  },
  identityChipLines: {
    position: "absolute",
    top: 6,
    left: 10,
    right: 10,
    height: 28,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderColor: "rgba(255,255,255,0.18)",
    borderRadius: 8,
  },
  identityChipCore: {
    position: "absolute",
    top: 11,
    left: 17,
    width: 24,
    height: 18,
    borderRadius: 4,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  identityArrow: {
    width: 0,
    height: 0,
    borderTopWidth: 16,
    borderBottomWidth: 16,
    borderRightWidth: 18,
    borderTopColor: "transparent",
    borderBottomColor: "transparent",
    borderRightColor: "#e4e9f2",
    marginTop: 30,
  },
  identityIdBlock: {
    display: "none",
  },
  identityValueSmall: {
    color: "#e6eaef",
    fontWeight: "800",
    fontSize: 12,
    lineHeight: 16,
  },
  identityInfo: {
    flex: 1,
    gap: 10,
    paddingLeft: 0,
    paddingRight: 80,
    marginLeft: -8,
    paddingTop: 10,
  },
  identityRow: {
    gap: 4,
  },
  identityLabel: {
    color: "#dfe4eb",
    fontWeight: "800",
    fontSize: 10.5,
    letterSpacing: 0.4,
  },
  identityValueMain: {
    color: "#eef2f7",
    fontWeight: "900",
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.2,
  },
  identityValue: {
    color: "#e2e7ee",
    fontWeight: "800",
    fontSize: 12,
    lineHeight: 16,
  },
  identityMini: {
    minWidth: 120,
    maxWidth: 200,
    gap: 2,
    alignItems: "flex-start",
    flex: 1,
  },
  identityDocLeft: {
    paddingTop: 8,
  },
  identityDocMiddle: {
    marginLeft: -6,
    paddingTop: 8,
  },
  identityDocRight: {
    alignItems: "flex-start",
    paddingTop: 8,
    marginLeft: -22,
  },
  silhouette: {
    position: "absolute",
    right: -16,
    top: -10,
    opacity: 0.92,
  },
  securityCard: {
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 18,
    padding: 18,
    gap: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
    shadowColor: "#0e241a",
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
  },
  sectionTitle: {
    color: colors.surface,
    fontWeight: "800",
    fontSize: 18,
  },
  sectionSubtitle: {
    color: "rgba(255,255,255,0.86)",
    lineHeight: 20,
  },
  form: {
    gap: 12,
    marginTop: 6,
  },
  input: {
    backgroundColor: "rgba(255,255,255,0.9)",
    borderColor: "rgba(13,27,42,0.18)",
    color: "#0d1b2a",
    borderRadius: 14,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  inputWrapper: {
    position: "relative",
    justifyContent: "center",
  },
  inputWithIcon: {
    paddingLeft: 48,
  },
  inputIcon: {
    position: "absolute",
    left: 16,
    zIndex: 1,
  },
  passwordToggle: {
    position: "absolute",
    right: 16,
    padding: 6,
  },
  cta: {
    backgroundColor: "#f7f7f7",
    borderRadius: 50,
    shadowColor: "#1a0f2a",
    shadowOpacity: 0.24,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
  },
  ctaText: {
    color: "#111827",
    fontWeight: "800",
  },
  tipPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(231,237,245,0.92)",
    borderWidth: 1,
    borderColor: "rgba(28,60,90,0.12)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 50,
  },
  tipText: {
    color: "#1a2f4b",
    fontWeight: "800",
    fontSize: 12,
  },
  backBadge: {
    display: "none",
  },
  backStrip: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 12,
    position: "relative",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.24)",
    shadowColor: "#0b273f",
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    minHeight: 86,
  },
  backStripLabel: {
    color: "#e7ebf0",
    fontSize: 11,
    fontWeight: "800",
    marginBottom: 8,
  },
  signatureStrip: {
    height: 32,
    backgroundColor: "rgba(255,255,255,0.16)",
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.26)",
  },
  cvvBox: {
    position: "absolute",
    right: 12,
    top: 26,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.52)",
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  cvvText: {
    color: "#eef1f6",
    fontWeight: "900",
    fontSize: 14,
    letterSpacing: 1,
  },
  backContact: {
    alignItems: "flex-end",
    gap: 2,
    paddingHorizontal: 6,
  },
  backWebsite: {
    color: "#e9ecf2",
    fontWeight: "800",
    fontSize: 13,
  },
  backPhone: {
    color: "#d4dae3",
    fontWeight: "700",
    fontSize: 12,
  },
  backMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 0,
    paddingHorizontal: 0,
    marginTop: "auto",
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
  },
  backChip: {
    width: 108,
    height: 60,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    marginLeft: 0,
    marginRight: 0,
    marginVertical: 0,
  },
  backBlurb: {
    flex: 1,
    gap: 0,
  },
  backBlurbText: {
    color: "#d0d7e0",
    fontSize: 12,
    lineHeight: 14,
  },
  backChipLogo: {
    width: 108,
    height: 60,
    tintColor: "#e7ebf0",
  },
});

export default styles;
